#!/bin/bash
#
# /media/fat/sysinfo2oled/S60sysinfo2oled
#
# 2021-04-19 by venice
# License GPL v3
# Release based on S60tty2oled
#

SCRIPT="sysinfo2oled.sh"
DAEMON="/media/fat/sysinfo2oled/${SCRIPT}"
INITSCRIPT="/media/fat/sysinfo2oled/S60sysinfo2oled"
USERSTARTUP="/media/fat/linux/user-startup.sh"
USERSTARTUPTPL="/media/fat/linux/_user-startup.sh"

# Start
start() {
    if [[ -x ${DAEMON} ]]; then
      echo "Starting sysinfo2oled..."
      ${DAEMON} &
    else
      echo "${DAEMON} not found!"
    fi
}

# Stop
stop() {
    echo "Stopping sysinfo2oled..."
    I2CINWPID=$(ps -eo pid,ppid,args | grep $(ps | grep ${SCRIPT} | awk 'NR==1{print $1}') | tail -1 | awk '{print $1}')
    #echo "PID inotifywait: ${I2CINWPID}"
    killall ${SCRIPT}
    kill ${I2CINWPID}
}

case "$1" in
  start)
        start
        ;;
  stop) 
        stop
        ;;
  restart)
        stop
        start
        ;;
  setup)
        if [ ! -e ${USERSTARTUP} ] && [ -e /etc/init.d/S99user ]; then
          if [ -e ${USERSTARTUPTPL} ]; then
            echo "Copying ${USERSTARTUPTPL} to ${USERSTARTUP}"
            cp ${USERSTARTUPTPL} ${USERSTARTUP}
          else
            echo "Creating ${USERSTARTUP}"
            echo -e "#!/bin/sh\n" > ${USERSTARTUP}
            echo -e 'echo "***" $1 "***"' >> ${USERSTARTUP}
          fi
        fi

        if [ $(grep -c "sysinfo2oled"  ${USERSTARTUP}) = "0" ]; then
          echo "Adding sysinfo2oled init to user-startup"
          echo -e "\n# Startup sysinfo2oled" >>  ${USERSTARTUP}
          echo -e "[[ -e ${INITSCRIPT} ]] && ${INITSCRIPT} \$1" >>  ${USERSTARTUP}
        fi
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|setup}"
        exit 1
        ;;
esac
